// <auto-generated />
using System;
using A_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A_DAL.Migrations
{
    [DbContext(typeof(CofffeeDbContext))]
    [Migration("20230320083027_v1.1")]
    partial class v11
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("A_DAL.Models.Ban", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("bans");
                });

            modelBuilder.Entity("A_DAL.Models.Ban_HD", b =>
                {
                    b.Property<Guid>("IdBan")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdHd")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("IdBan", "IdHd");

                    b.HasIndex("IdHd");

                    b.ToTable("ban_HDs");
                });

            modelBuilder.Entity("A_DAL.Models.HoaDon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdNv")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("datetime");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdNv");

                    b.ToTable("hoaDons");
                });

            modelBuilder.Entity("A_DAL.Models.KhuyenMai", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DkGiam")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("Nvarchar(100)");

                    b.Property<DateTime>("NgayBd")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayKt")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<decimal>("PhamTramGiam")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("SoTienGiam")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("khuyenMais");
                });

            modelBuilder.Entity("A_DAL.Models.LoaiSp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("loaiSps");
                });

            modelBuilder.Entity("A_DAL.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChucVu")
                        .HasColumnType("int");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaNv")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("nhanViens");
                });

            modelBuilder.Entity("A_DAL.Models.SanPham", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GiaBan")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<Guid>("IdKm")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdLoai")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdKm");

                    b.HasIndex("IdLoai");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("A_DAL.Models.SP_HD", b =>
                {
                    b.Property<Guid>("IdHd")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdSp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DonGia")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("IdHd", "IdSp");

                    b.HasIndex("IdSp");

                    b.ToTable("sP_HDs");
                });

            modelBuilder.Entity("A_DAL.Models.Ban_HD", b =>
                {
                    b.HasOne("A_DAL.Models.Ban", "Ban")
                        .WithMany("Ban_HDs")
                        .HasForeignKey("IdBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Ban");

                    b.HasOne("A_DAL.Models.HoaDon", "HoaDon")
                        .WithMany("Ban_HDs")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ban");

                    b.Navigation("HoaDon");
                });

            modelBuilder.Entity("A_DAL.Models.HoaDon", b =>
                {
                    b.HasOne("A_DAL.Models.NhanVien", "NhanVien")
                        .WithMany("HoaDons")
                        .HasForeignKey("IdNv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_NVHD");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("A_DAL.Models.SanPham", b =>
                {
                    b.HasOne("A_DAL.Models.KhuyenMai", "KhuyenMai")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdKm")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SPKM");

                    b.HasOne("A_DAL.Models.LoaiSp", "LoaiSp")
                        .WithMany("SanPhams")
                        .HasForeignKey("IdLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SPLoai");

                    b.Navigation("KhuyenMai");

                    b.Navigation("LoaiSp");
                });

            modelBuilder.Entity("A_DAL.Models.SP_HD", b =>
                {
                    b.HasOne("A_DAL.Models.HoaDon", "HoaDon")
                        .WithMany("SP_HDs")
                        .HasForeignKey("IdHd")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("A_DAL.Models.SanPham", "SanPham")
                        .WithMany("SP_HDs")
                        .HasForeignKey("IdSp")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SPHD");

                    b.Navigation("HoaDon");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("A_DAL.Models.Ban", b =>
                {
                    b.Navigation("Ban_HDs");
                });

            modelBuilder.Entity("A_DAL.Models.HoaDon", b =>
                {
                    b.Navigation("Ban_HDs");

                    b.Navigation("SP_HDs");
                });

            modelBuilder.Entity("A_DAL.Models.KhuyenMai", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("A_DAL.Models.LoaiSp", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("A_DAL.Models.NhanVien", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("A_DAL.Models.SanPham", b =>
                {
                    b.Navigation("SP_HDs");
                });
#pragma warning restore 612, 618
        }
    }
}
